import React, { useState, useEffect, useCallback } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import Swal from 'sweetalert2';
import api from '../../utils/api';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
    faClipboardList, faPlus, faSearch, faEdit, faTrash,
    faPaperclip, faClipboardCheck, faTimes, faFolderOpen, faBuilding, faRepeat, faUserPen
} from '@fortawesome/free-solid-svg-icons';
import Pagination from '../../components/Pagination';
import RecurringTaskList from '../../components/RecurringTaskList';
import SelfAssignedList from '../../components/SelfAssignedList';
import { slug, taskContextLabel } from '../../utils/taskHelpers';
import Avatar from '../../components/Avatar';
import TaskCountdown, { hasTimeWindow } from '../../components/TaskCountdown';
import '../../styles/App.css';
import '../../styles/tasks.css';
import '../../styles/taskCards.css';
import '../../styles/selftask.css';

const DEFAULT_FILTERS = { status: 'All', priority: 'All', projectId: 'All', taskType: 'All' };

// The progress bar reflects the task's shared status rather than a headcount.
const STATUS_PROGRESS = {
    'Pending': 0,
    'In Progress': 50,
    'On Hold': 50,
    'Completed': 100
};

const Tasks = () => {
    const navigate = useNavigate();
    const currentUser = JSON.parse(localStorage.getItem('user'));
    const isPrivileged = ['ADMIN', 'HR'].includes(currentUser?.role);
    const [searchParams] = useSearchParams();

    // 'tasks' lists work with its people attached; 'recurring' shows the daily
    // schedules rather than the individual tasks they generate. The
    // people-first view ("who has nothing assigned") moved to its own page,
    // Task Report, alongside the calendar.
    const VIEWS = ['tasks', 'recurring', 'self'];
    const [view, setView] = useState(() => {
        const v = searchParams.get('view');
        return VIEWS.includes(v) ? v : 'tasks';
    });

    // Drives the amber count on the Self-Assigned tab, so a manager can see
    // there is something waiting without opening it.
    const [pendingSelf, setPendingSelf] = useState(0);

    useEffect(() => {
        api.get('/tasks/self-assigned', { params: { approvalStatus: 'Pending', limit: 1 } })
            .then(res => setPendingSelf(res.data.pendingCount || 0))
            .catch(() => setPendingSelf(0));
    }, [view]);

    const [tasks, setTasks] = useState([]);
    const [projectsList, setProjectsList] = useState([]);
    const [loading, setLoading] = useState(true);

    const [filters, setFilters] = useState(DEFAULT_FILTERS);
    const [searchTerm, setSearchTerm] = useState('');
    const [debouncedSearch, setDebouncedSearch] = useState('');

    const [currentPage, setCurrentPage] = useState(1);
    const [totalPages, setTotalPages] = useState(1);
    const [totalRecords, setTotalRecords] = useState(0);
    const [itemsPerPage, setItemsPerPage] = useState(10);


    useEffect(() => {
        api.get('/tasks/assignable-projects')
            .then(res => setProjectsList(res.data || []))
            .catch(() => setProjectsList([]));
    }, []);

    useEffect(() => {
        const timer = setTimeout(() => setDebouncedSearch(searchTerm), 500);
        return () => clearTimeout(timer);
    }, [searchTerm]);

    useEffect(() => setCurrentPage(1), [debouncedSearch, filters]);

    const fetchTasks = useCallback(async () => {
        setLoading(true);
        try {
            const res = await api.get('/tasks/managed', {
                params: {
                    page: currentPage,
                    limit: itemsPerPage,
                    search: debouncedSearch,
                    // Days generated by a schedule belong to the Recurring tab;
                    // listing them here too would make the split meaningless.
                    excludeRecurring: true,
                    ...filters
                }
            });
            setTasks(res.data.data);
            setTotalPages(res.data.pagination.totalPages);
            setTotalRecords(res.data.pagination.totalRecords);
        } catch (err) {
            console.error('Failed to load tasks', err);
            Swal.fire('Error', 'Could not load tasks.', 'error');
        } finally {
            setLoading(false);
        }
    }, [currentPage, itemsPerPage, debouncedSearch, filters]);

    // The employee view loads its own data, so don't pay for this one while it's up.
    useEffect(() => {
        if (view === 'tasks') fetchTasks();
    }, [fetchTasks, view]);

    // Older notifications link here as /tasks?task=<id>; send them to the page.
    useEffect(() => {
        const taskId = searchParams.get('task');
        if (taskId) navigate(`/task/${taskId}`, { replace: true });
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);

    const handleFilterChange = (e) =>
        setFilters({ ...filters, [e.target.name]: e.target.value });

    const clearFilters = () => {
        setFilters(DEFAULT_FILTERS);
        setSearchTerm('');
    };

    const activeFilterCount =
        Object.keys(DEFAULT_FILTERS).filter(k => filters[k] !== 'All').length +
        (searchTerm ? 1 : 0);

    const handleDelete = async (task) => {
        const result = await Swal.fire({
            title: 'Remove this task?',
            text: `"${task.title}" will be archived and disappear from everyone's list.`,
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#dc2626',
            confirmButtonText: 'Yes, remove it'
        });
        if (!result.isConfirmed) return;

        try {
            await api.delete(`/tasks/${task._id}`);
            Swal.fire({
                icon: 'success', title: 'Task removed', toast: true,
                position: 'top-end', timer: 1800, showConfirmButton: false
            });
            fetchTasks();
        } catch (err) {
            Swal.fire('Error', err.response?.data?.message || 'Could not remove the task.', 'error');
        }
    };

    const isOverdue = (task) =>
        new Date(task.overdueAt || task.dueDate) < new Date() && task.status !== 'Completed';

    return (
        <div className="attendance-container fade-in">
            <div className="task-page-header">
                <h1 className="page-title header-no-margin">
                    <FontAwesomeIcon icon={faClipboardList} style={{ marginRight: '10px', color: '#215D7B' }} />
                    {isPrivileged ? 'All Tasks' : 'Assigned Tasks'}
                </h1>
                {/* Two kinds of task sit together in one group. Checking who is
                    carrying work is a different question, so it stands apart. */}
                <div className="task-view-group">
                    <div className="type-toggle view-toggle">
                        <button
                            type="button"
                            className={`type-toggle-btn ${view === 'tasks' ? 'active' : ''}`}
                            onClick={() => setView('tasks')}
                        >
                            <FontAwesomeIcon icon={faClipboardList} /> Regular Tasks
                        </button>
                        <button
                            type="button"
                            className={`type-toggle-btn ${view === 'recurring' ? 'active' : ''}`}
                            onClick={() => setView('recurring')}
                        >
                            <FontAwesomeIcon icon={faRepeat} /> Recurring Tasks
                        </button>
                        <button
                            type="button"
                            className={`type-toggle-btn ${view === 'self' ? 'active' : ''}`}
                            onClick={() => setView('self')}
                        >
                            <FontAwesomeIcon icon={faUserPen} /> Self-Assigned
                            {pendingSelf > 0 && <span className="sa-tab-count">{pendingSelf}</span>}
                        </button>
                    </div>
                </div>

                <button className="gts-btn primary" style={{ marginLeft: 'auto' }} onClick={() => navigate('/add-task')}>
                    <FontAwesomeIcon icon={faPlus} /> Assign Task
                </button>
            </div>

            {view === 'recurring' ? <RecurringTaskList /> : view === 'self' ? <SelfAssignedList /> : (
            <>

            {/* --- Search + filters in a single bar --- */}
            <div className="task-toolbar">
                <div className="task-toolbar-search">
                    <FontAwesomeIcon icon={faSearch} className="task-search-icon" />
                    <input
                        type="text"
                        placeholder="Search tasks by title or description..."
                        value={searchTerm}
                        onChange={(e) => setSearchTerm(e.target.value)}
                    />
                </div>

                <div className="task-toolbar-filters">
                    <select
                        className={`task-filter-select ${filters.status !== 'All' ? 'is-active' : ''}`}
                        name="status" value={filters.status} onChange={handleFilterChange}
                    >
                        <option value="All">All Statuses</option>
                        <option value="Pending">Pending</option>
                        <option value="In Progress">In Progress</option>
                        <option value="On Hold">On Hold</option>
                        <option value="Completed">Completed</option>
                    </select>

                    <select
                        className={`task-filter-select ${filters.priority !== 'All' ? 'is-active' : ''}`}
                        name="priority" value={filters.priority} onChange={handleFilterChange}
                    >
                        <option value="All">All Priorities</option>
                        <option value="Low">Low</option>
                        <option value="Medium">Medium</option>
                        <option value="High">High</option>
                        <option value="Urgent">Urgent</option>
                    </select>

                    <select
                        className={`task-filter-select ${filters.taskType !== 'All' ? 'is-active' : ''}`}
                        name="taskType" value={filters.taskType} onChange={handleFilterChange}
                    >
                        <option value="All">All Types</option>
                        <option value="Project Task">Project Task</option>
                        <option value="Regular Office Task">Regular Office</option>
                    </select>

                    <select
                        className={`task-filter-select ${filters.projectId !== 'All' ? 'is-active' : ''}`}
                        name="projectId" value={filters.projectId} onChange={handleFilterChange}
                    >
                        <option value="All">All Projects</option>
                        {projectsList.map(p => <option key={p._id} value={p._id}>{p.name}</option>)}
                    </select>

                    {activeFilterCount > 0 && (
                        <button className="task-filter-clear" onClick={clearFilters}>
                            <FontAwesomeIcon icon={faTimes} /> Clear ({activeFilterCount})
                        </button>
                    )}
                </div>
            </div>

            {!loading && totalRecords > 0 && (
                <div className="task-result-count">
                    Showing {tasks.length} of {totalRecords} task{totalRecords === 1 ? '' : 's'}
                    {activeFilterCount > 0 && ' (filtered)'}
                </div>
            )}

            {loading ? (
                <div className="control-card text-center" style={{ padding: '50px 20px', color: '#64748b' }}>
                    Loading tasks...
                </div>
            ) : tasks.length === 0 ? (
                <div className="control-card text-center" style={{ padding: '60px 20px' }}>
                    <FontAwesomeIcon icon={faClipboardCheck} style={{ fontSize: '3.5rem', color: '#cbd5e1', marginBottom: '15px' }} />
                    <h3 style={{ color: '#475569' }}>
                        {activeFilterCount > 0 ? 'No matching tasks' : 'No tasks yet'}
                    </h3>
                    <p className="text-muted">
                        {activeFilterCount > 0
                            ? 'Try clearing your filters to see everything.'
                            : 'Assign your first task to get started. Daily repeating work lives under Recurring Tasks.'}
                    </p>
                    {activeFilterCount > 0 && (
                        <button className="gts-btn secondary" style={{ marginTop: '12px' }} onClick={clearFilters}>
                            <FontAwesomeIcon icon={faTimes} /> Clear filters
                        </button>
                    )}
                </div>
            ) : (
                <div className="tgrid">
                    {tasks.map((task, idx) => {
                        const pct = STATUS_PROGRESS[task.status] ?? 0;
                        const overdue = isOverdue(task);
                        // Overdue outranks the work status on the stripe — it's
                        // the thing that needs acting on.
                        const tone = task.status === 'Completed' ? 'green'
                            : overdue ? 'red'
                                : task.status === 'In Progress' ? 'blue'
                                    : task.status === 'On Hold' ? 'amber' : 'grey';

                        return (
                            <div
                                key={task._id}
                                className={`tcard tone-${tone}`}
                                style={{ animationDelay: `${Math.min(idx * 18, 220)}ms` }}
                                onClick={() => navigate(`/task/${task._id}`)}
                            >
                                <div className="tcard-head">
                                    <div className="tcard-titlewrap">
                                        <span className="tcard-title" title={task.title}>{task.title}</span>
                                        <div className="tcard-badges">
                                            <span className={`task-status-badge ${slug(task.status)}`}>{task.status}</span>
                                            <span className={`priority-badge ${slug(task.priority)}`}>{task.priority}</span>
                                            {overdue && <span className="task-status-badge blocked">Overdue</span>}
                                            {task.isSelfAssigned && (
                                                <span className="ap-badge self" title="The employee logged this themselves">
                                                    <FontAwesomeIcon icon={faUserPen} /> Self Assigned
                                                </span>
                                            )}
                                            {task.attachments?.length > 0 && (
                                                <span className="task-media-count">
                                                    <FontAwesomeIcon icon={faPaperclip} /> {task.attachments.length}
                                                </span>
                                            )}
                                        </div>
                                    </div>

                                    <div className="tcard-actions" onClick={(e) => e.stopPropagation()}>
                                        <button
                                            className="icon-btn" title="Edit task" aria-label="Edit task"
                                            onClick={() => navigate(`/edit-task/${task._id}`)}
                                        >
                                            <FontAwesomeIcon icon={faEdit} />
                                        </button>
                                        <button
                                            className="icon-btn danger" title="Remove task" aria-label="Remove task"
                                            onClick={() => handleDelete(task)}
                                        >
                                            <FontAwesomeIcon icon={faTrash} />
                                        </button>
                                    </div>
                                </div>

                                <div className="tcard-meta">
                                    {/* Holds either a project name or "Regular Office",
                                        so the icon carries the distinction. */}
                                    <div className="tcard-field">
                                        <span className="tcard-label">Type / Project</span>
                                        <span className="tcard-value">
                                            <span className={`task-context ${task.taskType === 'Regular Office Task' ? 'is-office' : ''}`}>
                                                <FontAwesomeIcon icon={task.taskType === 'Regular Office Task' ? faBuilding : faFolderOpen} />
                                                <span className="task-context-label">{taskContextLabel(task)}</span>
                                            </span>
                                        </span>
                                    </div>

                                    <div className="tcard-field">
                                        <span className="tcard-label">Due date</span>
                                        <span className="tcard-value">
                                            <span className={`task-due-date ${overdue ? 'overdue' : ''}`}>
                                                {new Date(task.dueDate).toLocaleDateString('en-GB')}
                                            </span>
                                        </span>
                                        {hasTimeWindow(task) && <TaskCountdown task={task} compact />}
                                    </div>

                                    <div className="tcard-field">
                                        <span className="tcard-label">Assigned to</span>
                                        <span className="tcard-value">
                                            <span className="avatar-stack" title={task.assignees.map(a => a?.name).join(', ')}>
                                                {task.assignees.slice(0, 4).map(a => (
                                                    <Avatar key={a._id} name={a?.name} profilePic={a?.profilePic} className="assignee-avatar" />
                                                ))}
                                                {task.assignees.length > 4 && (
                                                    <span className="assignee-avatar avatar-more">+{task.assignees.length - 4}</span>
                                                )}
                                            </span>
                                        </span>
                                    </div>

                                    <div className="tcard-field">
                                        <span className="tcard-label">Assigned by</span>
                                        <span className="tcard-value is-muted">
                                            {task.assignedBy?.name ? (
                                                <span className="tcard-person">
                                                    <Avatar name={task.assignedBy.name} profilePic={task.assignedBy.profilePic} className="assignee-avatar" />
                                                    <span className="tcard-ellipsis">{task.assignedBy.name}</span>
                                                </span>
                                            ) : '—'}
                                        </span>
                                    </div>
                                </div>

                                <div className="tcard-foot">
                                    <span className="tcard-label">Progress</span>
                                    <div className="task-progress">
                                        <div className="task-progress-track">
                                            <div
                                                className={`task-progress-fill ${slug(task.status)}`}
                                                style={{ width: `${pct}%` }}
                                            />
                                        </div>
                                        <span className="task-progress-label">{pct}%</span>
                                    </div>
                                </div>
                            </div>
                        );
                    })}
                </div>
            )}

            {!loading && totalRecords > 0 && (
                <Pagination
                    currentPage={currentPage}
                    totalPages={totalPages}
                    totalRecords={totalRecords}
                    limit={itemsPerPage}
                    onPageChange={setCurrentPage}
                    onLimitChange={(val) => { setItemsPerPage(val); setCurrentPage(1); }}
                />
            )}

            </>
            )}

        </div>
    );
};

export default Tasks;
