const mongoose = require('mongoose');

const TASK_STATUSES = ['Pending', 'In Progress', 'On Hold', 'Completed'];
const TASK_TYPES = ['Project Task', 'Regular Office Task'];

// A single image/video attached to a task.
// Images go straight to S3. Videos are staged on the VPS first (`url` points at
// /uploads/tasks/...) and only swap to an S3 url after the nightly compression
// job runs — that's why `status` exists.
const mediaSchema = new mongoose.Schema({
    url: { type: String, required: true },
    fileName: { type: String, default: "" },
    type: { type: String, enum: ['image', 'video'], required: true },
    status: {
        type: String,
        enum: ['ready', 'processing_compression', 'failed'],
        default: 'ready'
    },
    // Only set on completion proof — who submitted this piece of evidence.
    uploadedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' }
});

const taskSchema = new mongoose.Schema({
    title: { type: String, required: true, trim: true },
    description: { type: String, default: "" },

    // Mirrors Expense.expenseType — not all work belongs to a client project.
    taskType: {
        type: String,
        enum: ['Project Task', 'Regular Office Task'],
        default: 'Project Task'
    },

    // Only meaningful for project work; office tasks leave this null.
    projectId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Project',
        required: function () { return this.taskType === 'Project Task'; }
    },
    assignedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },

    priority: {
        type: String,
        enum: ['Low', 'Medium', 'High', 'Urgent'],
        default: 'Medium'
    },

    // One status for the whole task. However many people are on it, they are
    // working towards the same outcome — whoever moves it, moves it for everyone.
    status: {
        type: String,
        enum: TASK_STATUSES,
        default: 'Pending'
    },
    statusNote: { type: String, default: "" },
    statusUpdatedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
    completedAt: { type: Date },

    startDate: { type: Date },
    dueDate: { type: Date, required: true },

    attachments: [mediaSchema],
    completionProof: [mediaSchema],

    // Simple membership list — everyone here shares the one status above.
    assignees: [{ type: mongoose.Schema.Types.ObjectId, ref: 'User' }],

    /**
     * Self-assigned work (TaskPlan.md §15).
     *
     * An employee logging work they were given verbally. `assignedBy` carries
     * whoever they name as having handed it to them, exactly as it does on a
     * manager-created task — the field already means the right thing.
     *
     * approvalStatus defaults to 'Approved' so every task that already exists,
     * and every task a manager creates, is unaffected with no migration.
     */
    isSelfAssigned: { type: Boolean, default: false },
    approvalStatus: {
        type: String,
        enum: ['Approved', 'Pending', 'Rejected'],
        default: 'Approved'
    },
    approvalNote: { type: String, default: "" },
    approvedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null },
    approvedAt: { type: Date, default: null },

    // Set only on tasks generated by a recurring schedule (TaskPlan.md §13).
    // A generated task is an ordinary task in every other respect — these two
    // fields exist so it can find its brief and report back to the schedule.
    recurringTaskId: { type: mongoose.Schema.Types.ObjectId, ref: 'RecurringTask', default: null },
    occurrenceDate: { type: String, default: null },   // YYYY-MM-DD

    isArchived: { type: Boolean, default: false }
}, { timestamps: true });

// The list views constantly ask "tasks for this user" and "tasks I created".
taskSchema.index({ assignees: 1, isArchived: 1 });
taskSchema.index({ assignedBy: 1, isArchived: 1 });
taskSchema.index({ status: 1, isArchived: 1 });

/**
 * The one index this feature cannot work without.
 *
 * node-cron does not fire while the process is down, so recurringTaskCron also
 * runs a catch-up sweep on boot — which means a restart shortly after 06:00 can
 * genuinely try to generate the same day twice. This makes the second attempt a
 * duplicate-key error the cron swallows, rather than a second copy of today's
 * task landing on someone's board.
 *
 * The partial filter is load-bearing: without it every ordinary task (which has
 * recurringTaskId: null and occurrenceDate: null) would collide with every
 * other ordinary task on the very first insert.
 */
taskSchema.index(
    { recurringTaskId: 1, occurrenceDate: 1, assignees: 1 },
    { unique: true, partialFilterExpression: { recurringTaskId: { $type: 'objectId' } } }
);

// The admin's Self-Assigned tab: "what is waiting on me to approve".
taskSchema.index({ isSelfAssigned: 1, approvalStatus: 1, isArchived: 1 });

// Feeding the schedule's compliance view.
taskSchema.index({ recurringTaskId: 1, occurrenceDate: 1 });

module.exports = mongoose.model('Task', taskSchema);
module.exports.TASK_STATUSES = TASK_STATUSES;
module.exports.TASK_TYPES = TASK_TYPES;
module.exports.APPROVAL_STATUSES = ['Approved', 'Pending', 'Rejected'];
// Reused verbatim by RecurringTask so a brief's attachments and a task's
// attachments can never drift apart in shape.
module.exports.mediaSchema = mediaSchema;
